rest:
  listenAddress: "localhost"
  port: 8000
  enableSwagger: true
  gracefulTimeout: 10
  readTimeout: 10
  writeTimeout: 10
  appName: "Shipdeo Balance"

mongo:
  uri: mongodb://127.0.0.1:27017
  db: lizbeth
  connectionTimeout: 10
  pingTimeout: 3

snowflake:
  epoch: 1626670674000
  pod_id: 1

spotify:
  credentials:
    scope: "user-read-private user-read-email playlist-read-collaborative playlist-modify-public playlist-read-private playlist-modify-private app-remote-control user-modify-playback-state user-read-playback-state user-read-currently-playing"
    authorizeCallbackUrl: "http://localhost:8000/auth/callback"
    clientId: "3514d9d987d947158cdba4e3e6426e61"
    clientSecret: "cabdb32109de4bed8221223371d9746f"
  coreApi:
    httpConfig:
      baseUrl: "https://api.spotify.com/v1"
      timeout: 3
      retryCount: 3
    endpoints:
      queue_track: "me/player/queue"
      get_user_info: "me"
  authApi:
    httpConfig:
      baseUrl: "https://accounts.spotify.com"
      timeout: 3
      retryCount: 3
    endpoints:
      authorize: "authorize"
      token: "api/token"

telegramBotApi:
  token: "5597215324:AAHfj4xkz65zWvi439oKIb65tE_lHyi2saI"
  debug: true
  timeout: 60
  updateOffset: 0

